### ISSUE TITLE
Support for info.json without a `dependencies` property

### ISSUE THREAD

**Issue by cameronleger** [redruin1/factorio-draftsman#10]
Some mods, like [VehicleSnap](https://mods.factorio.com/mod/VehicleSnap/downloads), don't include this property at all. I'm not sure if it would truly work without the `base` enabled, so I'm not sure if this should _assume_ that was meant or treat it like an empty array.

**Comment by redruin1** [comment]
After doing a little digging, it seems that mods that specify no dependencies seem to default to a single dependency, the `base` mod.
If I treat VehicleSnap with actually no dependencies, I get the following load order (because `base` depends on `core`):
```
['VehicleSnap', 'base', 'miniloader']
```
This differs from what I see in the factorio log, however:
```
   0.486 Loading mod settings miniloader 1.15.6 (settings.lua)
   0.486 Loading mod settings VehicleSnap 1.18.4 (settings.lua)
   0.488 Loading mod core 0.0.0 (data.lua)
   0.589 Loading mod base 1.1.59 (data.lua)
   0.850 Loading mod miniloader 1.15.6 (data.lua)
   0.942 Loading mod VehicleSnap 1.18.4 (data.lua)
   1.037 Loading mod base 1.1.59 (data-updates.lua)
   1.126 Loading mod miniloader 1.15.6 (data-updates.lua)
```
By setting dependencies to default to `["base"]` if not set, I get the correct output from `draftsman-update`:
```
Load order:
['base', 'miniloader', 'VehicleSnap']
SETTINGS.LUA:
        mod: miniloader
        mod: VehicleSnap
SETTINGS-UPDATES.LUA:
SETTINGS-FINAL-FIXES.LUA:
DATA.LUA:
        mod: base
        mod: miniloader
        mod: VehicleSnap
DATA-UPDATES.LUA:
        mod: base
        mod: miniloader
```
I suppose this makes sense, as the base mod cannot be disabled, and making a Factorio mod without Factorio itself seems to defeat the purpose somewhat. This will be fixed in `0.9.4`.
